### ISSUE TITLE
[v2.0] Should we create new format for X584 programs?

### ISSUE THREAD

**Issue by danil-kondr2016** [kodemeister/X584#35]
Since we propose to split comments from control flow statements (#21) and since 2.0 transites to Unicode should we create new version of X584 format with different extension and/or different magic number to distinguish one from another?

**Comment by kodemeister** [comment]
Well, I'm not convinced that making yet another format just for extra comments is a good idea. Just imagine if, say, Photoshop created a new format on every release, e.g. `.psd`, `.psdx`, `.psd2`, `.psd3`... It would be a total mess for users, to say the least.

It's almost always better to extend the existing format rather than creating a zoo of incompatible formats. Let's try to stick with old `.x584` files for now. I've added a small note to #21 about another possible way to extend `.x584` format that allows to store comments in Unicode in particular.

**Comment by danil-kondr2016** [comment]
Resolved in #36, implemented extension for X584 file format
